#!/usr/bin/env python3
# compliance/generate-soc2-report.py — Auto-generate SOC2 compliance report

import os
from datetime import datetime
from weasyprint import HTML, CSS

def generate_report():
    today = datetime.now().strftime('%Y-%m-%d')
    
    html = f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>SOC2 Compliance Report — {today}</title>
  <style>
    body {{ font-family: sans-serif; padding: 2em; max-width: 900px; margin: 0 auto; }}
    h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; }}
    .control {{ background: #f8f9fa; border-left: 4px solid #3498db; padding: 1em; margin: 1em 0; }}
    .evidence {{ font-family: monospace; background: #eee; padding: 0.2em 0.4em; }}
  </style>
</head>
<body>
  <h1>🔐 SOC2 Compliance Report — {today}</h1>
  
  <div class="control">
    <h2>CC6.1 — Logical Access</h2>
    <p><strong>Evidence:</strong> Role-based access control enforced in <span class="evidence">multi-tenant/rbac.py</span> and immutable audit logging in <span class="evidence">security/audit/immutable-log.py</span>.</p>
  </div>
  
  <div class="control">
    <h2>CC7.2 — Change Management</h2>
    <p><strong>Evidence:</strong> All code changes deployed via CI/CD with approval gates in <span class="evidence">.github/workflows/ci-cd.yml</span>. Audit logs signed and retained 90 days per <span class="evidence">security/retention-policy.md</span>.</p>
  </div>
  
  <div class="control">
    <h2>CC8.1 — Data Loss Prevention</h2>
    <p><strong>Evidence:</strong> Daily encrypted backups to S3/MinIO in <span class="evidence">backup/backup-to-s3.sh</span>. Zero data exfiltration — all processing local.</p>
  </div>
  
  <p style="margin-top: 2em; font-size: 0.9em; color: #7f8c8d;">
    Generated by OpenClaw v0.1.10 • Policy+FX Trust Layer • <a href="https://github.com/PUYUAM/policyfx-trust">github.com/PUYUAM/policyfx-trust</a>
  </p>
</body>
</html>"""
    
    HTML(string=html).write_pdf(f'compliance/soc2-report-{today}.pdf')
    print(f'✅ SOC2 report generated: compliance/soc2-report-{today}.pdf')

if __name__ == '__main__':
    generate_report()
